name: Samed Panel Builder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi Kopyala
        uses: actions/checkout@v4

      - name: Java 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Dosyasini Calistirilabilir Yap
        run: chmod +x gradlew

      - name: APK Derle (Debug)
        run: ./gradlew assembleDebug

      - name: APK Dosyasini Sisteme Yukle
        uses: actions/upload-artifact@v4
        with:
          name: SamedPanel-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
