name: Samed Panel APK Kesin Cozum
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v4

      - name: Java 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Proje Yapisini ve Gradle'i Sifirdan Kur
        run: |
          # 1. Klasörleri temizce oluştur
          mkdir -p app/src/main/java/com/samed/panel
          mkdir -p app/src/main/res/layout

          # 2. Dosyaları (küçük/büyük harf bakmadan) yerlerine taşı
          find . -maxdepth 2 -iname "mainactivity.java" -exec mv {} app/src/main/java/com/samed/panel/MainActivity.java \;
          find . -maxdepth 2 -iname "bootreceiver.java" -exec mv {} app/src/main/java/com/samed/panel/BootReceiver.java \;
          find . -maxdepth 2 -iname "activity_main.xml" -exec mv {} app/src/main/res/layout/activity_main.xml \;
          find . -maxdepth 2 -iname "androidmanifest.xml" -exec mv {} app/src/main/AndroidManifest.xml \;

          # 3. Ayar dosyalarını otomatik oluştur (Hata payını sıfırlar)
          echo "android.useAndroidX=true" > gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "include ':app'" > settings.gradle
          
          echo "buildscript { 
            repositories { google(); mavenCentral() }
            dependencies { classpath 'com.android.tools.build:gradle:8.2.0' }
          }
          allprojects { repositories { google(); mavenCentral() } }" > build.gradle

          echo "plugins { id 'com.android.application' }
          android {
              namespace 'com.samed.panel'
              compileSdk 34
              defaultConfig {
                  applicationId 'com.samed.panel'
                  minSdk 21
                  targetSdk 34
                  versionCode 1
                  versionName '1.0'
              }
          }
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'com.google.android.material:material:1.9.0'
          }" > app/build.gradle

          # 4. EKSİK OLAN MOTORU (WRAPPER) SIFIRDAN KUR
          gradle wrapper --gradle-version 8.5

      - name: APK Derle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon

      - name: APK Dosyasini Yukle
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Samed-Panel-APK
          path: app/build/outputs/apk/debug/app-debug.apk
