name: Samed Panel APK Builder

on:
  push:
    branches: [ "main", "master" ] # main veya master fark etmeksizin çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi Kopyala
        uses: actions/checkout@v4

      - name: Java 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Dosyalar gerçekten yerinde mi diye kontrol eder (Hata ayıklama için)
      - name: Dosya Yapısını Listele
        run: ls -R

      - name: Gradle Calistirma Izinlerini Ver
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
          else
            echo "HATA: gradlew dosyası ana dizinde bulunamadı!"
            exit 1
          fi

      - name: APK Derle
        run: ./gradlew assembleDebug --stacktrace

      - name: APK'yı Sisteme Yukle
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: SamedPanel-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk
